package com.mercotrace.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TraderAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTraderAllPropertiesEquals(Trader expected, Trader actual) {
        assertTraderAutoGeneratedPropertiesEquals(expected, actual);
        assertTraderAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTraderAllUpdatablePropertiesEquals(Trader expected, Trader actual) {
        assertTraderUpdatableFieldsEquals(expected, actual);
        assertTraderUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTraderAutoGeneratedPropertiesEquals(Trader expected, Trader actual) {
        assertThat(actual)
            .as("Verify Trader auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTraderUpdatableFieldsEquals(Trader expected, Trader actual) {
        assertThat(actual)
            .as("Verify Trader relevant properties")
            .satisfies(a -> assertThat(a.getBusinessName()).as("check businessName").isEqualTo(expected.getBusinessName()))
            .satisfies(a -> assertThat(a.getOwnerName()).as("check ownerName").isEqualTo(expected.getOwnerName()))
            .satisfies(a -> assertThat(a.getAddress()).as("check address").isEqualTo(expected.getAddress()))
            .satisfies(a -> assertThat(a.getCategory()).as("check category").isEqualTo(expected.getCategory()))
            .satisfies(a -> assertThat(a.getApprovalStatus()).as("check approvalStatus").isEqualTo(expected.getApprovalStatus()))
            .satisfies(a -> assertThat(a.getBusinessMode()).as("check businessMode").isEqualTo(expected.getBusinessMode()))
            .satisfies(a -> assertThat(a.getBillPrefix()).as("check billPrefix").isEqualTo(expected.getBillPrefix()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getUpdatedAt()).as("check updatedAt").isEqualTo(expected.getUpdatedAt()))
            .satisfies(a -> assertThat(a.getPresetEnabled()).as("check presetEnabled").isEqualTo(expected.getPresetEnabled()))
            .satisfies(a -> assertThat(a.getActive()).as("check active").isEqualTo(expected.getActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTraderUpdatableRelationshipsEquals(Trader expected, Trader actual) {
        // empty method
    }
}
